### ISSUE TITLE
Can't start dev server - incorrect Gatsby dependency

### ISSUE THREAD

**Issue by AX-LLaidley** [Redocly/developer-portal-starter#99]
Since upgrading to the latest version of developer-portal (1.0.0-beta.154), my development server no longer functions. When I  run `yarn start` I get 2 warnings stating `warn Plugin gatsby-remark-image-attributes is not compatible with your gatsby version 3.7.2 - It requires gatsby@^2.0.0` and then the process fails with an error:

```
Missing onError handler for invocation 'building-schema', error was 'Error: Cannot create as TypeComposer the following value:
  Date.'. Stacktrace was 'Error: Cannot create as TypeComposer the following value:
  Date.
    at SchemaComposer.createTempTC (/Users/llaidley/Projects/devportal-trial/node_modules/graphql-compose/lib/SchemaComposer.js:463:11)
    at SchemaComposer.createTC (/Users/llaidley/Projects/devportal-trial/node_modules/graphql-compose/lib/SchemaComposer.js:426:84)
    at SchemaComposer.add (/Users/llaidley/Projects/devportal-trial/node_modules/graphql-compose/lib/SchemaComposer.js:715:21)
    at createSchemaComposer (/Users/llaidley/Projects/devportal-trial/node_modules/@redocly/developer-portal/node_modules/gatsby/src/schema/schema-composer.js:16:18)
    at build (/Users/llaidley/Projects/devportal-trial/node_modules/@redocly/developer-portal/node_modules/gatsby/src/schema/index.js:104:26)
    at buildSchema (/Users/llaidley/Projects/devportal-trial/node_modules/@redocly/developer-portal/node_modules/gatsby/src/services/build-schema.ts:19:3)'
```
This is followed by the terminal hanging on `building schema`

For the moment, I'm going to try rolling my repo back to whichever previous version that works. Any chance we can get this fixed asap? Thanks in advance.

**Comment by RomanHotsiy** [comment]
Should be resolved in beta.155.
Apologize for the trouble.

**Comment by AX-LLaidley** [comment]
I tried upgrading to beta.155, but still getting the same error. The only
difference is that I'm no longer seeing the warnings first.

<https://www.automox.com/?utm_campaign=ax_email&utm_medium=internal&utm_source=automox>

Laurie Laidley (she/her)
API Technical Documentation Writer

Dir: 860.574.4536
1401 Walnut St. Suite 300
Boulder, CO 80302

Join the expert community for cyber hygiene. Sign up now for Automox Alive
<http://bit.ly/communityemailsig>!

**Comment by RomanHotsiy** [comment]
We will dig into it, thanks for your response.

**Comment by RomanHotsiy** [comment]
Should be fixed on beta.156.
